name: Build macOS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Download Catalina directly from Apple
        run: |
          mkdir -p ~/catalina
          curl -L "https://swcdn.apple.com/content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/InstallESDDmg.pkg" -o ~/catalina/InstallESDDmg.pkg
          curl -L "https://swcdn.apple.com/content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/BaseSystem.dmg" -o ~/catalina/BaseSystem.dmg

      - name: Create ISO
        run: |
          hdiutil create -o /tmp/Catalina -size 8500m -volname "Catalina" -layout SPUD -fs HFS+J
          hdiutil attach /tmp/Catalina.dmg -noverify -mountpoint /Volumes/Catalina
          sudo installer -pkg ~/catalina/InstallESDDmg.pkg -target /Volumes/Catalina
          hdiutil detach /Volumes/Catalina
          hdiutil convert /tmp/Catalina.dmg -format UDTO -o /tmp/CatalinaFinal
          mv /tmp/CatalinaFinal.cdr /tmp/Catalina.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: Catalina-ISO
          path: /tmp/Catalina.iso
